# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
         node-version: [12.x]
      
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout do codigo do projeto
      - uses: actions/checkout@v2
      
      # Setup do Node JS
      - name: Setup Node.js enviroment
        uses: actions/setup-node@2.1.1
        with:
          node-version: ${{ matrix.node-version }}
          
          # instalando as dependecias 
        - run: npm install
        
        # Executar os testes usando o cucumber
        - run: npm run cy:run:cucumber
        
        # gerar o relatorio em HTML
        - run: npm run report:cucumber
        
        # publicar relatorio em HTML
        - name: Deploy to GithumPages
          uses: JamesIves/github-pages-deploy-action@3.5.9
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: cypress/reports
        
